language: node_js
node_js:
- 6
- 7
- 8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
  code_climate:
    repo_token:
      secure: Ew9Pi/cVS/herXT082k3E/xwcpI8BORzgQpcLCdtir7nXqRRi7g0HOR31OH375+xO4F5sJLGKNSK5zJ1iSJvxChJXdwU4e2ZEgTlbm8z7Ewh7kd39dGg+JIqwcIrqpIXyniqbw6Ntu6Jwk8QjQXgbtkYwNw35WxsLGEF7fKY41M=
env:
  global:
    - CXX=g++-4.8
script:
- "./node_modules/istanbul/lib/cli.js cover ./node_modules/mocha/bin/_mocha tests/"
- (cat coverage/lcov.info | ./node_modules/codeclimate-test-reporter/bin/codeclimate.js) || (echo Code climate failed - not criticial)

